---
output:
  pdf_document: default
---

# CONTEXT AND BACKGROUND

Topic: The relationship between good interactive statistical graphics using Gestalt principles to develop effective dashboards. 

**What is the current situation?**

Data visualization is an essential tool in the field of data analysis, allowing researchers and decision-makers to gain insights and make well-informed choices. 
In recent years, extensive research has been conducted on statistical interactive graphics and Gestalt principles, which provide useful frameworks for designing effective visualizations. 
However, there is a lack of research on the intersection of these fields with dashboards, which are increasingly used for real-time data monitoring and decision making.

**What is wrong with the situation and/or what needs to change?** 

Many Dashboards are built to assist in data exploration, but many dashboards lack guidelines and appropriate perception with static and interactive statistical graphics. 


**What are the most recent events that led us to the current situation?**

The field of data visualization is in a constant state of evolution, and researchers are always looking for ways to enhance data communication through visual means. 
There is a growing demand for efficient methods that enable users to explore complex data, especially in business intelligence and scientific research. 

**What is the setting of the problem?**

This research aims to contribute to the development and improvement of dashboards that convey complex data and information to users effectively.


# KNOWLEDGE GAP


**What have researchers in similar settings explored or discovered?**

While statistical interactive graphics allow for the manipulation and exploration of complex data sets, Gestalt principles offer a framework for understanding how visual elements are perceived and organized by the human brain. 
The integration of these two fields can lead to more effective and efficient dashboards that take into account human perception and cognition.


**What have researchers in other settings explored or discovered?** 

By utilizing the principles of Gestalt psychology, which explain how humans perceive and interpret visual information, and incorporating statistical interactive graphics, which enable users to interact with data in dynamic ways, we can create data visualizations that are not only aesthetically pleasing but also effective at communicating complex information.


**What remains unknown about the problem?** 

While it is known that interactive graphics is an essential aspect of statistical graphics and are used in dashboard designs frequently, the inconsistency gap between interactive graphics and dashboard design. 
As a result, it is unknown whether there is a relationship between interactive graphics and effective dashboard design can be implemented in Exploratory Data Analysis (EDA).

# SIGNIFICANCE


**Why is it important to fill the knowledge gap?**

This body of work's findings will have implications for researchers, practitioners, and decision-makers who rely on data visualizations to effectively communicate information. 
By identifying best practices and design guidelines for integrating statistical interactive graphics, Gestalt principles, and dashboards, this research can contribute to the development of more effective data visualization tools that aid in decision-making across multiple domains.

**Scope: How big is the problem, and how many people are affected in the field or specific context you are studying?**

Gestalt principles describe how the human brain organizes visual data into meaningful patterns (Ware, 2012). 
These principles are essential for designing effective visualizations that can communicate complex data in a straightforward and simple manner. 
In contrast, statistical interactive graphics enable users to explore large datasets by permitting interaction with visual representations of the data. 
Dashboards are increasingly used in a variety of fields to provide users with real-time data insights and analysis, facilitating data-driven decision making (Few, 2013).

**Consequences: What are the consequences of not addressing the problem?**

Dashboards will continue to be designed without the appropriate perception of good statistical interactive graphics when analysts develop dashboards for exploring large data. 
In addition, disregarding perception laws, such as Gestalt principles, can result in poorly designed visuals that fail to convey the intended message. 

**Contribution: How will your study contribute to the problem’s solution? How does filling the gap help?**

Overall, it is crucial to bridge the gap between statistical interactive graphics, Gestalt principles, and dashboards to ensure that visualizations are effective, user-friendly, and provide valuable insights to the user.

# Draft Problem Statement




